Create chat views between users
rupesh-ps/mini-project pull request #7
Opened 2024-11-18 05:26 UTC by rupesh-ps

## PR Title: Create chat views between users 

### Description

This PR includes the below:
- **Create views for chat**: Created `chat_detail` and `inbox` views with their templates.
-  **Edit/Delete feature**: User can edit/delete their messages with a time constraint.
- **User Testing**: Verified the functionality of views with real users.
- **Quick Message Button**: Added a "new message" button under user profiles to start new chat, easily.

2024-11-20 05:08 UTC, shantanutomarr requested changes

2024-11-20 05:08 UTC, shantanutomarr commented on adBridge/ad_chat/views.py
> +def chat_detail(request, chat_id):
Write this as class-based view with small methods. Extract code into smaller chunks with meaningful names.

2024-11-20 11:38 UTC, rupesh-ps commented on adBridge/ad_chat/views.py
> +def chat_detail(request, chat_id):
Refactored the code.

2024-11-21 05:46 UTC, shantanutomarr requested changes

2024-11-21 05:46 UTC, shantanutomarr commented on adBridge/ad_chat/views.py
> +class MessageService:
Since this is used by only a single view, you can move it inside the vide itself. No need for separate class.

2024-11-21 05:46 UTC, shantanutomarr commented on adBridge/ad_chat/views.py
> +class MessagePermissions:
Same as above

2024-11-21 05:46 UTC, shantanutomarr commented on adBridge/ad_chat/views.py
> +                return self.send_new_message(request, message_text, chat)
Extract to separate method with meaningful name.

2024-11-21 05:46 UTC, shantanutomarr commented on adBridge/ad_chat/views.py
> +                messages.error(request, 'You can only delete your own messages.')
Extract to separate method with meaningful name.

2024-11-26 04:55 UTC, shantanutomarr approved these changes

2024-11-26 04:56 UTC, merged